const countryImages = {
    Argentina: require('../assets/imgs/Pages/Country-Images/Country-Images/Argentina.jpg'),
    Australia: require('../assets/imgs/Pages/Country-Images/Country-Images/Australia.png'),
    Belgium: require('../assets/imgs/Pages/Country-Images/Country-Images/Belgium.png'),
    Brazil: require('../assets/imgs/Pages/Country-Images/Country-Images/brazil.jpg'),
    Canada: require('../assets/imgs/Pages/Country-Images/Country-Images/Canada.png'),
    Denmark: require('../assets/imgs/Pages/Country-Images/Country-Images/Denmark.png'),
    France: require('../assets/imgs/Pages/Country-Images/Country-Images/France.png'),
    Germany: require('../assets/imgs/Pages/Country-Images/Country-Images/Germany.png'),
    Greece: require('../assets/imgs/Pages/Country-Images/Country-Images/Greece.png'),
    Hungary: require('../assets/imgs/Pages/Country-Images/Country-Images/Hungary.png'),
    Iceland: require('../assets/imgs/Pages/Country-Images/Country-Images/Iceland.png'),
    India: require('../assets/imgs/Pages/Country-Images/Country-Images/india.jpg'),
    Ireland: require('../assets/imgs/Pages/Country-Images/Country-Images/Ireland.png'),
    Italy: require('../assets/imgs/Pages/Country-Images/Country-Images/Italy.png'),
    Luxembourg: require('../assets/imgs/Pages/Country-Images/Country-Images/Luxembourg.png'),
    Peru: require('../assets/imgs/Pages/Country-Images/Country-Images/Peru.png'),
    Colombia: require('../assets/imgs/Pages/Country-Images/Country-Images/Colombia.png'),
    UK: require('../assets/imgs/Pages/Country-Images/Country-Images/UK.jpg'),
    Uruguay: require('../assets/imgs/Pages/Country-Images/Country-Images/Uruguay.png'),
    Ecuador: require('../assets/imgs/Pages/Country-Images/Country-Images/Ecuador.png'),
    USA: require('../assets/imgs/Pages/Country-Images/Country-Images/usa.jpg'),
    Japan: require('../assets/imgs/Pages/Country-Images/Country-Images/Japan.jpg'),
    NewZealand: require('../assets/imgs/Pages/Country-Images/Country-Images/NewZealand.jpg'),
    SouthAfrica: require('../assets/imgs/Pages/Country-Images/Country-Images/SouthAfrica.jpg'),
    chooseimgbg: require('../ServicesDetails/Service-MiniSlider-Imgs/chooseimgbg.png'),
};

export default countryImages;
